name: Public Release

on:
  release:
    types: [published]

jobs:
  public-release:
    name: "Public Release"
    runs-on: ubuntu-latest
    steps:
    - name: copy_asset
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        regex: true
        file: "^.*.uf2"
        token: ${{ secrets.GITHUB_TOKEN }}


    - name: Check Files
      run: ls

    - name: Push to Another repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-directory: '.'
        destination-github-username: 'Playtronica'
        destination-repository-name: 'biotron-releases'

  

      
        
  
